- platform: flux
  lights:
    - light.lounge_ceiling_1
    - light.lounge_ceiling_2
    - light.Lounge_fireplace_1
    - light.lounge_fireplace_2
  name: Lounge Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  mode: mired
  transition: 30
  interval: 120

- platform: flux
  lights:
    - light.living_room_ceiling_1
    - light.living_room_ceiling_2
    - light.living_room_ceiling_3
  name: Livingroom Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  mode: mired
  transition: 30
  interval: 120

- platform: flux
  lights:
    - light.kitchen_ceiling_3
  name: Kitchen Cupboard Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  mode: mired
  transition: 30
  interval: 120

- platform: flux
  lights:
    - light.kitchen_ceiling_1
    - light.kitchen_ceiling_2
  name: Kitchen Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  mode: mired
  transition: 30
  interval: 120

- platform: flux
  lights:
    - light.hall_ceiling_1
    - light.hall_ceiling_2
    - light.hall_ceiling_3
  name: Hall Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  transition: 30
  mode: mired
  interval: 120
