services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./config:/config
      - /dev/serial/by-id/:/dev/serial/by-id
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=America/Los_Angeles
    healthcheck:
      test: ["CMD", "curl", "--fail", http://localhost:8123]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 60s

  home-assistant-home-proxy:
    image: ghcr.io/gitgc/home-proxy-webserver:main
    container_name: home-assistant-home-proxy
    restart: unless-stopped
    init: true
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DO_AUTH_TOKEN
      - CADDY_SUBDOMAIN
      - CADDY_DOMAIN
      - CADDY_PROXY_UPSTREAM
      - CADDY_HEALTH_CHECK_URI
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./caddy/data/:/data/"
      - "./caddy/config/:/config/"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "${CADDY_HEALTH_CHECK_URI}" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - home-assistant

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_SCHEDULE
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
