services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./config:/config
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=America/Los_Angeles
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - NEST_CLIENT_ID
      - NEST_CLIENT_SECRET
      - NEST_PROJECT_ID
      - NEST_SUBSCRIBER_ID
    healthcheck:
      test: ["CMD", "curl", "--fail", http://localhost:8123]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 60s

  caddy:
    build: ./caddy
    container_name: home-assistant-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DO_AUTH_TOKEN
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./caddy/site/:/var/www/html/"
      - "./caddy/caddy_data/:/data/"
      - "./caddy/caddy_config/:/config/"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost/caddy-health-check" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - home-assistant
