- alias: Frigate mobile notifications
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
    value_template: '{{ value_json.type }}'
  condition: []
  action:
  - service: notify.carrie_gio
    data_template:
      message: A {{trigger.payload_json["after"]["label"]}} was detected on {{trigger.payload_json["after"]["camera"]}}
      data:
        image: https://5tup05ato1u047sgwytbxn2m36omtn3u.ui.nabu.casa/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        entity_id: camera.{{trigger.payload_json["after"]["camera"]|replace('-', '_')}}
  mode: single
  id: d7bb2a87510f42ee8e0bcc202a562ef2
- alias: Kitchen doorbell press notifications
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 4bc3180bff566c2898d13453c8bc3cba
    entity_id: binary_sensor.front_door_doorbell
    domain: binary_sensor
  condition: []
  action:
  - service: notify.carrie_gio
    data_template:
      message: Kitchen Door Bell is ringing
      data:
        image: https://nvr.coia.me/frigate/api/front-door/latest.jpg?h=600
        tag: '{{trigger["id"]}}'
        when: '{{trigger["to_state"]["last_changed"]}}'
  mode: single
  id: 1e93c6186792430784aff898ec7975e7
- alias: car/person porch lights at night
  description: ''
  condition:
    condition: or
    conditions:
    - condition: time
      after: '20:30'
    - condition: sun
      before: sunrise
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity:
      - binary_sensor.front_door_car_motion
      - binary_sensor.front_door_person_motion
      - binary_sensor.workshop_yard_car_motion
      - binary_sensor.workshop_yard_person_motion
      light_target:
        entity_id: light.porch_lights
      no_motion_wait: 6000
  id: 56db549eda6849aba1a33561117b89ab
- alias: Re-enable Frigate Notifications
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: time
    at: '23:59:00'
  - platform: time
    at: 03:00:00
  - platform: time
    at: 09:00:00
  - platform: time
    at: '13:00:00'
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.front_door_person_notification_2
  mode: single
  id: 060bf8c83f0745fc8bb66160ca21b98d
- alias: Set theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: synthwave
  id: 31a567274592472db41444e2a0524c13
- id: '1661058288902'
  alias: Living Room person detection
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_person_motion
    for:
      hours: 0
      minutes: 0
      seconds: 0
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_living_room
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_kitchen
    metadata: {}
  mode: single
