- id: d7bb2a87510f42ee8e0bcc202a562ef2
  alias: Frigate mobile notifications
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
    value_template: '{{ value_json.type }}'
  condition: '{{ trigger.payload_json["after"]["camera"] not in [''living-room'',''dining-room'']
    }}

    '
  action:
  - service: notify.carrie_gio
    data_template:
      message: A {{trigger.payload_json["after"]["label"]}} was detected on {{trigger.payload_json["after"]["camera"]}}
      data:
        image: https://5tup05ato1u047sgwytbxn2m36omtn3u.ui.nabu.casa/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        entity_id: camera.{{trigger.payload_json["after"]["camera"]|replace('-', '_')}}
  mode: single
- alias: Kitchen doorbell press notifications
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 4bc3180bff566c2898d13453c8bc3cba
    entity_id: binary_sensor.front_door_doorbell
    domain: binary_sensor
  condition: []
  action:
  - service: notify.carrie_gio
    data_template:
      message: Kitchen Door Bell is ringing
      data:
        image: https://nvr.coia.me/frigate/api/front-door/latest.jpg?h=600
        tag: '{{trigger["id"]}}'
        when: '{{trigger["to_state"]["last_changed"]}}'
  mode: single
  id: 1e93c6186792430784aff898ec7975e7
- alias: Re-enable Frigate Notifications
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: time
    at: '23:59:00'
  - platform: time
    at: 03:00:00
  - platform: time
    at: 09:00:00
  - platform: time
    at: '13:00:00'
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.front_door_person_notification_2
  mode: single
  id: 060bf8c83f0745fc8bb66160ca21b98d
- alias: Set theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: synthwave
  id: 31a567274592472db41444e2a0524c13
- id: '1661058288902'
  alias: Living Room person detection
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_person
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: light.wiz_rgbw_tunable_15b7f3
    state: 'off'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_living_room
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_kitchen
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_dining_room
    metadata: {}
  mode: single
- id: '1661224459838'
  alias: Living Room Light Switch Button 1 - Lights On
  description: ''
  trigger:
  - device_id: 0f6ad86fc58d296fca994fd893cdb950
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 51030216-26d1-4db3-9f7c-65f8562783a1
  - device_id: 1b71d18276e6d153e4222da407e6ba91
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: d9889503-27b5-46ee-860a-3d93b0462895
  - device_id: 0e63805a40b605c9ae2068ba04d1ddb9
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: f3d7214a-c408-4488-ab7c-be90910b5c2b
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_living_room
    metadata: {}
  mode: single
- id: '1661224545628'
  alias: Living Room Light Switch Button 4 - Lights Off
  description: ''
  trigger:
  - device_id: 0f6ad86fc58d296fca994fd893cdb950
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: a80f5b5a-2930-48de-a6a1-067dc7e3e1b2
  - device_id: 1b71d18276e6d153e4222da407e6ba91
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: f3dcf760-7ecd-47f2-9172-060cd375a1c2
  - device_id: 0e63805a40b605c9ae2068ba04d1ddb9
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: ac6ffb20-d2a5-44c8-a260-f11c64f109b8
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_kitchen
    metadata: {}
  mode: single
- id: '1661224732948'
  alias: Dining Room Light Switch Button 1 - Lights On
  description: ''
  trigger:
  - device_id: da00fd7437f015ef175a1bb6670ce99c
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: c5a43c01-66ff-425c-b060-efe8f9e2b0eb
  - device_id: f2fa82394f60db28af38a3d0f23f71c8
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: f372ecb9-ee39-4514-81ea-15f70b38cac5
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_dining_room
    metadata: {}
  mode: single
- id: '1661224792408'
  alias: Dining Room Light Switch Button 4 - Lights Off
  description: ''
  trigger:
  - device_id: da00fd7437f015ef175a1bb6670ce99c
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: a6da19bd-57d7-4f1c-a97c-da1a264fd7ae
  - device_id: f2fa82394f60db28af38a3d0f23f71c8
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: b939771f-8efd-4443-9061-6a649a0a31ff
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_dining_room
    metadata: {}
  mode: single
- id: '1661224903229'
  alias: Midnight Shutdown
  description: ''
  trigger:
  - platform: time
    at: '23:59:00'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.good_night
    metadata: {}
  mode: single
- id: '1661224993479'
  alias: Kitchen Light Switch Button 1 - Lights On
  description: ''
  trigger:
  - device_id: 2ee76cdaf6be02d157844b5c88b7c60e
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 66b2821f-b7ff-441a-8c6c-a45dd5dfdb9b
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_kitchen
    metadata: {}
  mode: single
- id: '1661225119449'
  alias: Kitchen Light Switch Button 4 - Lights Off
  description: ''
  trigger:
  - device_id: 2ee76cdaf6be02d157844b5c88b7c60e
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: 1ea41760-6840-4655-9963-89b9ddd65325
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_kitchen
    metadata: {}
  mode: single
- id: '1661225156170'
  alias: Hall Light Switch Button 1 - Lights On
  description: ''
  trigger:
  - device_id: e6e5519dff32648ece893aa4a1820425
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 8d62558a-b5e5-430b-9406-207098a23cd6
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_hall
    metadata: {}
  mode: single
- id: '1661225274569'
  alias: Hall Light Switch Button 4 - Lights Off
  description: ''
  trigger:
  - device_id: e6e5519dff32648ece893aa4a1820425
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: c16445f9-d221-4636-ad24-3740d68f7b1d
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_hall
    metadata: {}
  mode: single
- id: '1661400245461'
  alias: Dining Room person detection
  description: ''
  trigger:
  - platform: state
    entity_id:
    - camera.dining_room_person
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: light.wiz_rgbw_tunable_14cfde
    state: 'off'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_living_room
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_kitchen
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_dining_room
    metadata: {}
  mode: single
- id: '1662847764038'
  alias: Dining Lights Switch Button 1
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: d6d06725819a5980355d6dd650d9588b
    entity_id: switch.lumi_lumi_switch_b2naus01_switch
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_dining_room
    metadata: {}
  mode: single
- id: '1662847872037'
  alias: Dining Light Switch button 2
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: d6d06725819a5980355d6dd650d9588b
    entity_id: switch.lumi_lumi_switch_b2naus01_switch_2
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_kitchen
    metadata: {}
  mode: single
- id: '1662847922646'
  alias: dining light switch button 2 0ff
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: d6d06725819a5980355d6dd650d9588b
    entity_id: switch.lumi_lumi_switch_b2naus01_switch_2
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_kitchen
    metadata: {}
  mode: single
- id: '1662847960419'
  alias: Dining Light Switch button 2 off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: d6d06725819a5980355d6dd650d9588b
    entity_id: switch.lumi_lumi_switch_b2naus01_switch
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_dining_room
    metadata: {}
  mode: single
- id: '1662925758797'
  alias: Motion - Dining Room
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 9dfe890ee9fa54e354bf079e6ac36d20
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_dining_room
    metadata: {}
  mode: single
- id: '1662927853231'
  alias: Motion - kitchen lights
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 6c01eab2e98a0857525d0c79be9dcc50
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_2
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_kitchen
    metadata: {}
  mode: single
- id: '1662928886415'
  alias: Motion - living room lights
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: bb1e52009f9db63c0965f4aaf8919612
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_3
    domain: binary_sensor
  - type: occupied
    platform: device
    device_id: 556c4d3174bdb001b1c5b5f5f318402a
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_4
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_living_room
    metadata: {}
  mode: single
- id: '1662932857661'
  alias: Motion stops - lights off dining room
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: 9dfe890ee9fa54e354bf079e6ac36d20
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_dining_room
    metadata: {}
  mode: single
- id: '1662932910765'
  alias: motion stops - kitchen lights
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: 6c01eab2e98a0857525d0c79be9dcc50
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_2
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_kitchen
    metadata: {}
  mode: single
- id: '1662932943432'
  alias: motion stops - living room lights off
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: bb1e52009f9db63c0965f4aaf8919612
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_3
    domain: binary_sensor
  - type: not_occupied
    platform: device
    device_id: 556c4d3174bdb001b1c5b5f5f318402a
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_4
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_living_room
    metadata: {}
  mode: single
- id: '1662935487512'
  alias: motion - hall lights on
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: ea806f0b40d036b9fc3729da2f321dfd
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_5
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_hall
    metadata: {}
  mode: single
- id: '1662935510192'
  alias: Motion stops - hall lights off
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: ea806f0b40d036b9fc3729da2f321dfd
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_5
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_hall
    metadata: {}
  mode: single
- id: '1663029994130'
  alias: Kitchen Light Switch - Kitchen Lights on
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: c38a513b5c0940202e5d44bb2fc7cb58
    entity_id: switch.lumi_lumi_switch_b2naus01_switch_3
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_kitchen
    metadata: {}
  mode: single
- id: '1663030062863'
  alias: Kitchen light switch 2 living lights on
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: c38a513b5c0940202e5d44bb2fc7cb58
    entity_id: switch.lumi_lumi_switch_b2naus01_switch_4
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_living_room
    metadata: {}
  mode: single
- id: '1663030791130'
  alias: kitchen sw2 living lights off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: c38a513b5c0940202e5d44bb2fc7cb58
    entity_id: switch.lumi_lumi_switch_b2naus01_switch_4
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_living_room
    metadata: {}
  mode: single
- id: '1663030835681'
  alias: kitchen sw1 - kitchen lights off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: c38a513b5c0940202e5d44bb2fc7cb58
    entity_id: switch.lumi_lumi_switch_b2naus01_switch_3
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_kitchen
    metadata: {}
  mode: single
- id: '1663037277157'
  alias: Living Room Coffee Table Button
  description: ''
  trigger:
  - platform: device
    device_id: 9092fade5aa9c815122aa3010c051d68
    domain: button
    entity_id: button.living_room_coffee_table_button_identifybutton
    type: pressed
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_movie
    metadata: {}
  mode: single
- id: '1663048473703'
  alias: Carrie bedside button double
  description: ''
  trigger:
  - device_id: 9a69d3054ff067b069251f52e774e8cc
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.good_night
    metadata: {}
  mode: single
- id: '1663048595840'
  alias: Carrie bedside single
  description: ''
  trigger:
  - device_id: 9a69d3054ff067b069251f52e774e8cc
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.good_morning
    metadata: {}
  mode: single
- id: '1663550981224'
  alias: Tag Kitchen Door is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 5b5dd504-d454-4ebc-aee4-ba0a9eb8ed13
  - platform: device
    device_id: ae390be0bd10ff23381d071779c29d1c
    domain: lock
    entity_id: lock.kitchen_door_lock
    type: unlocked
  condition: []
  action: []
  mode: single
- id: '1663551121270'
  alias: Tag Kitchen Door is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 5b5dd504-d454-4ebc-aee4-ba0a9eb8ed13
  condition: []
  action:
  - device_id: ae390be0bd10ff23381d071779c29d1c
    domain: lock
    entity_id: lock.kitchen_door_lock
    type: unlock
  mode: single
- id: '1664155599103'
  alias: auto front lights
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 9cc8d87224fa066d156136d89bd3ad9b
    entity_id: binary_sensor.garage_yard_all_occupancy
    domain: binary_sensor
  - type: occupied
    platform: device
    device_id: 82145e615170adfca48f08e1f75460f4
    entity_id: binary_sensor.workshop_yard_all_occupancy
    domain: binary_sensor
  - type: occupied
    platform: device
    device_id: 1e2de10a0ee0327774e622c054837c09
    entity_id: binary_sensor.front_door_all_occupancy
    domain: binary_sensor
  - type: value
    platform: device
    device_id: 1e2de10a0ee0327774e622c054837c09
    entity_id: sensor.front_door_car_count
    domain: sensor
    above: 0
  - type: value
    platform: device
    device_id: 82145e615170adfca48f08e1f75460f4
    entity_id: sensor.workshop_yard_car_count
    domain: sensor
    above: 0
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_porch
    metadata: {}
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_porch
    metadata: {}
  mode: single
- id: '1668394084841'
  alias: Giga desk single tap
  description: ''
  trigger:
  - device_id: d9f90fb9a405d0f33c46d858b1e175a3
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_den
    metadata: {}
  mode: single
- id: '1668394128135'
  alias: giga desk double tap
  description: ''
  trigger:
  - device_id: d9f90fb9a405d0f33c46d858b1e175a3
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off_den
    metadata: {}
  mode: single
