
default_config:

frontend:
  themes: !include_dir_merge_named themes/synthwave

lovelace:
  resources:
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.18.0.2

notify: !include notify.yaml

logger:
    default: warning

tts: !include tts.yaml
climate: !include climate.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
switch: !include switches.yaml

spotify: !include spotify.yaml
nest: !include nest.yaml
