- platform: flux
  lights:
    - light.wiz_rgbw_tunable_380239
    - light.wiz_rgbw_tunable_38021f
    - light.wiz_rgbw_tunable_158816
    - light.wiz_rgbw_tunable_158821
  name: Lounge Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  mode: mired
  transition: 15
  interval: 30

- platform: flux
  lights:
    - light.wiz_rgbw_tunable_14cfde
    - light.wiz_rgbw_tunable_15b7f3
    - light.wiz_rgbw_tunable_1587f5
  name: Livingroom Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  mode: mired
  transition: 15
  interval: 30

- platform: flux
  lights:
    - light.wiz_tunable_white_165b58
    - light.wiz_tunable_white_163ec9
  name: Kitchen Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  mode: mired
  transition: 15
  interval: 30

- platform: flux
  lights:
    - light.wiz_rgbw_tunable_38d2bb
    - light.wiz_rgbw_tunable_14ee32
    - light.wiz_rgbw_tunable_158831
  name: Hall Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2000
  transition: 15
  mode: mired
  interval: 30
