- platform: group
  name: Porch Lights
  entities:
    - light.wiz_rgbw_tunable_fa1a3c
    - light.wiz_rgbw_tunable_158800
    - light.wiz_rgbw_tunable_14a7a5
    - light.wiz_rgbw_tunable_14d02a

- platform: group
  name: Lounge Ceiling Lights
  entities:
    - light.wiz_rgbw_tunable_380239
    - light.wiz_rgbw_tunable_38021f
    - light.wiz_rgbw_tunable_158816
    - light.wiz_rgbw_tunable_158821

- platform: group
  name: Dining Table Lights
  entities:
    - light.wiz_dimmable_white_9edc6e
    - light.wiz_dimmable_white_9eaef2
    - light.wiz_dimmable_white_9ec902
    - light.wiz_dimmable_white_9ef8d3
    - light.wiz_dimmable_white_9ed387
    - light.wiz_dimmable_white_9ee773
    - light.wiz_dimmable_white_9eb6bb
    - light.wiz_dimmable_white_9eb7de

- platform: group
  name: Kitchen Counter Lights
  entities:
    - light.wiz_dimmable_white_9ea440
    - light.wiz_dimmable_white_9edddd
    - light.wiz_dimmable_white_9f0230

- platform: group
  name: Kitchen Ceiling Lights
  entities:
    - light.wiz_tunable_white_165b58
    - light.wiz_tunable_white_163ec9

- platform: group
  name: Livingroom Ceiling Lights
  entities:
    - light.wiz_rgbw_tunable_14cfde
    - light.wiz_rgbw_tunable_15b7f3
    - light.wiz_rgbw_tunable_1587f5

- platform: group
  name: Livingroom Fireplace Lights
  entities:
    - light.living_room_fireplace_1
    - light.living_room_fireplace_2

- platform: group
  name: Hallway Ceiling Lights
  entities:
    - light.wiz_rgbw_tunable_38d2bb
    - light.wiz_rgbw_tunable_14ee32
    - light.wiz_rgbw_tunable_158831

- platform: group
  name: Bedroom Door Lights
  entities:
    - light.hue_ambiance_lamp_3
    - light.hue_ambiance_lamp_2